language: python
python:
  - "2.7"
before_script:
  - sudo redis-server /etc/redis/redis.conf --port 6379
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install coveralls
# command to run tests
script: nosetests -v --with-coverage --cover-package=sdh
branches:
  only:
    - master
    - develop
after_success:
  coveralls